name: Made Indra
bio: Learning is my long life mission
description: Shower Thought
external-image: false
picture: assets/images/profile.jpg
resume: false
resume-external: true
resume-url: 'https://google.com/?q=my+resume'
url: 'https://madeindra.github.io'
permalink: '/:title/'
disqus:
  shortname: madecanggih
  categories:
    - blog
    - project
youtube: madecanggih
github: madeindra
email: madeindra@pm.me
authors:
  madeindra:
    name: Made Indra
    bio: Still learning to be a better developer
    external-image: false
    picture: assets/images/profile.jpg
    twitter: indrawp
width: normal
pagination:
  enabled: false
  sort_reverse: true
  title: ':title'
  per_page: 5
  permalink: '/:num/'
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
defaults:
  - scope:
      path: ''
      layout: post
    values:
      hidden: false
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - node_modules
  - vendor
